export const QUEUE_NAMES = {
  TRANSCRIPT_PROCESSING: 'transcript.processing',
  DOCUMENT_GENERATION: 'document.generation',
  EMBEDDING_GENERATION: 'embedding.generation',
  NOTIFICATION_SEND: 'notification.send',
  INTEGRATION_SYNC: 'integration.sync',
} as const;

export const ROLES_KEY = 'roles';
export const IS_PUBLIC_KEY = 'isPublic';

export const ERROR_CODES = {
  TRANSCRIPT_NOT_AVAILABLE: 'TRANSCRIPT_NOT_AVAILABLE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SPEAKER_ATTRIBUTION_DISABLED: 'SPEAKER_ATTRIBUTION_DISABLED',
  TENANT_POLICY_BLOCKED: 'TENANT_POLICY_BLOCKED',
  AI_PROCESSING_FAILED: 'AI_PROCESSING_FAILED',
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
} as const;
